require "sinatra"
require "json"
require "fileutils"
require "redcarpet"
require "dotenv/load"
require_relative "../ruby_chromatic_agent/agent"

MARKDOWN = Redcarpet::Markdown.new(
  Redcarpet::Render::HTML.new(link_attributes: { target: "_blank", rel: "noopener noreferrer" }),
  autolink: true,
  tables: true,
  fenced_code_blocks: true,
  strikethrough: true,
  no_intra_emphasis: true
)

SESSION_FILE = File.join(__dir__, "data", "session.json")

$display_messages = []
$agent = ChromaticAgent.new

set :public_folder, File.join(__dir__, "public")
set :views, File.join(__dir__, "views")

def save_session
  FileUtils.mkdir_p(File.dirname(SESSION_FILE))
  agent_msgs = $agent.messages.map do |m|
    content = if m[:content].is_a?(String)
      m[:content]
    else
      block = m[:content].find do |b|
        b.is_a?(Hash) ? b[:type].to_s == "text" || b["type"].to_s == "text" : b.type.to_s == "text"
      end
      if block.is_a?(Hash)
        (block[:text] || block["text"]).to_s
      else
        block&.text.to_s
      end
    end
    { role: m[:role], content: content }
  end
  File.write(SESSION_FILE, JSON.generate({
    display:        $display_messages,
    agent_messages: agent_msgs,
    session:        SESSION.to_h
  }))
end

def load_session
  return unless File.exist?(SESSION_FILE)
  data = JSON.parse(File.read(SESSION_FILE), symbolize_names: true)
  $display_messages = (data[:display] || []).map { |m| { role: m[:role].to_s, text: m[:text].to_s } }
  agent_msgs = (data[:agent_messages] || []).map { |m| { role: m[:role].to_s, content: m[:content].to_s } }
  $agent = ChromaticAgent.new(messages: agent_msgs)
  s = data[:session] || {}
  (s[:artists]    || []).each { |n| SESSION.add_artist(n) }
  (s[:palettes]   || []).each { |n| SESSION.add_palette(n) }
  (s[:techniques] || []).each { |n| SESSION.add_technique(n) }
  (s[:styles]     || []).each { |n| SESSION.add_style(n) }
end

load_session

get "/" do
  @display_messages = $display_messages
  erb :index
end

post "/chat" do
  content_type :json

  body = JSON.parse(request.body.read)
  message = body["message"].to_s.strip
  halt 400, { error: "Message cannot be empty." }.to_json if message.empty?

  raw = $agent.chat(message)
  $display_messages << { role: "user", text: message }
  $display_messages << { role: "agent", text: raw }
  save_session

  { response: MARKDOWN.render(raw), summary: SESSION.summary }.to_json
rescue => e
  status 500
  { error: e.message }.to_json
end

post "/reset" do
  content_type :json
  $display_messages = []
  $agent = ChromaticAgent.new
  SESSION.reset!
  File.delete(SESSION_FILE) if File.exist?(SESSION_FILE)
  { ok: true }.to_json
end

get "/export" do
  s = SESSION.to_h
  lines = [
    "# Chromatic Agent Session",
    "",
    "_Exported: #{Time.now.strftime('%B %d, %Y')}_",
    ""
  ]

  unless SESSION.is_empty?
    lines << "## What We Explored"
    lines << ""
    lines << "**Artists:** #{s[:artists].join(', ')}"    unless s[:artists].empty?
    lines << "**Palettes:** #{s[:palettes].join(', ')}"  unless s[:palettes].empty?
    lines << "**Techniques:** #{s[:techniques].join(', ')}" unless s[:techniques].empty?
    lines << "**Styles:** #{s[:styles].join(', ')}"      unless s[:styles].empty?
    lines << ""
  end

  if $display_messages.any?
    lines << "## Conversation"
    lines << ""
    $display_messages.each do |msg|
      label = msg[:role] == "user" ? "**You**" : "**Chromatic**"
      lines << "#{label}: #{msg[:text]}"
      lines << ""
    end
  end

  lines << "---"
  lines << "_Generated by Chromatic Agent_"

  content_type "text/markdown"
  filename = "chromatic-session-#{Time.now.strftime('%Y%m%d')}.md"
  headers["Content-Disposition"] = "attachment; filename=\"#{filename}\""
  lines.join("\n")
end
